services:
  projection-db:
    image: postgres:14.1-alpine
    container_name: postgres-akka-restaurant-reviews
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - '8016:5432'
    volumes:
      - projection-db:/var/lib/postgresql11/data
      - ./projection-db-scripts/init-scripts.sql:/docker-entrypoint-initdb.d/scripts.sql

  cassandra:
    image: cassandra:3
    container_name: cassandra-akka-restaurant-reviews
    ports:
      - "7000:7000"
      - "9042:9042"
    environment:
      - "CASSANDRA_CLUSTER_NAME=OUR_DOCKERIZED_CASSANDRA_SINGLE_NODE_CLUSTER"


volumes:
  projection-db:
    driver: local
