services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - "TZ=America/New_York"
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
    ports:
      - "8000:8000"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"

  cassandra:
    image: cassandra:3
    container_name: cassandra
    ports:
      - "7000:7000"
      - "9042:9042"
    environment:
      - "CASSANDRA_CLUSTER_NAME=OUR_DOCKERIZED_CASSANDRA_SINGLE_NODE_CLUSTER"